---
name: List all default GitHub var

on:
    workflow_dispatch:

jobs:
    ubuntu-environment-variable:
        runs-on: ubuntu-latest
        steps:
        - run: env

    windows-environment-variable:
        runs-on: windows-latest
        steps:
        - run: env
    macos-environment-variable:
        runs-on: macos-latest
        steps:
        - run: env
