---
name: 'Custom Env Var'
on: 
 workflow_dispatch:
env:
 DAYS_OF_THE_WEEK= Funday
 testvar: value-1

jobs: 
 mainjobs: 
   name: 'print the env vars'
   runs-on: ubuntu-latest

   env: 
   greetings: Dear
   testvar: value-2
   
   
