---
  name: 'Custom Env Var'

  on:
    workflow_dispatch:

  env:
    DAYS_OF_THE_WEEK: Sunday
    testvar: value-1

  jobs:
    main_job:
      name: 'print the env vars'
      runs-on: ubuntu-latest

      env:
        Greeting: Dear
        testvar: value-2

      steps:
      - name: print-values-of-the-env-vars
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "testvar $testvar"
          echo "testvar ${{ env.testvar }}"
        env:
            First_Name: Student
            testvar: value-3
